#!/bin/sh
GREEN='\033[0;32m'
BLUE='\033[0;34m'
# RED='\033[0;31m'
NC='\033[0m'

WORK_DIR="$HOME/projects/spika"
DEST_DIR="/mnt/c/Users/xorgal/Desktop"
PACKAGE_FILENAME="Spika.zip"

clear
cd ${WORK_DIR}
echo "${GREEN}Building${BLUE} Spika Wallet${GREEN} Google Chrome extension package...${NC}"
npm run build:release

echo "${GREEN}Copying ${BLUE}manifest.json${GREN} and extension files to ./dist directory...${NC}"
mv ./dist/background.js ./dist/app
mv ./dist/content.js ./dist/app
mv ./dist/inpage.js ./dist/app
cp ./src/assets/spika_logo_16.png ./dist/app/assets
cp ./src/assets/spika_logo_48.png ./dist/app/assets
echo "${GREEN}Creating${BLUE} ${PACKAGE_FILENAME}${GREEN} package for Chrome Web Store...${NC}"
zip -r ${PACKAGE_FILENAME} ./dist
echo "${GREEN}Destination directory set to${BLUE} ${DEST_DIR}${NC}"
echo "${GREEN}Moving ${BLUE}dist${GREEN} directory and ${BLUE}${PACKAGE_FILENAME}${GREEN} package to ${BLUE}${DEST_DIR}${GREEN}...${NC}"
rm -rf ${DEST_DIR}/dist
rm ${DEST_DIR}/${PACKAGE_FILENAME}
cp -r ./dist ${DEST_DIR}
mv ./${PACKAGE_FILENAME} ${DEST_DIR}
echo "${GREEN}All tasks completed.${NC}"
